spring.application.name=module2

spring.h2.console.enabled=true

spring.datasource.url=jdbc:h2:file:C:/Users/GtothaV/Desktop/Coding Shuttle Modules/Coding-Shuttle-Course-Repo/Module 2/src/main/Database
spring.datasource.username=V2thaG
spring.datasource.password=1Pogchamp

spring.jpa.hibernate.ddl-auto = update